# Generated by Django 6.1 on 2026-10-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_historicostatus_options_pedido_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupcake',
            name='imagem_estatica',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
